--[==[badge-app
slug=flybadge
name=FlyBadge
icon=FLY
api=2
heap_kb=96
wake_lock=1
version=1.0
author=FlyBrain Rover
]==]

-- FlyBadge -- a real fruit fly's escape circuit, running on your badge.
--
-- The neurons and synapses below are not a model of a fly and not a trained network. They are measured
-- anatomy: a subsample of the male Drosophila CNS connectome (neuPrint male-cns:v1.0, Berg et al. 2026).
-- LC4 and LPLC2 are the looming detectors in the fly's optic lobe. They converge on the giant fibre, the
-- single neuron whose spike launches an escape jump. That convergence is what fires when you swat at a fly
-- and miss, and it is wired here exactly as it is wired in the animal, with the real synapse counts and
-- the real signs.
--
--   swat at the badge   -> the accelerometer sees it -> current into LC4 and LPLC2
--   giant fibre spikes  -> every LED flashes and the fly jumps
--   B                   -> zero the outgoing synapses of LC4 and LPLC2 (a lesion). Swat all you like.
--   A                   -> put them back
--   UP / DOWN           -> sensitivity, saved between runs
--
-- There is no flinch rule anywhere in this file. Deleting the lesion check would not leave a hidden
-- reflex behind, because the escape only ever came out of the wiring.
--
-- The membrane equation runs in integers: the ESP32-C3 has no floating point unit, so one unit is 1/256
-- of a millivolt and the decay factors are 8-bit fractions. badge/sim_fixed.py runs this same arithmetic
-- on a laptop against this same circuit file, which is how the constants were chosen.

-- flybadge_circuit.lua -- GENERATED by badge/export_badge_circuit.py, do not edit.
-- A subsample of the male Drosophila CNS connectome (neuPrint male-cns:v1.0): 150 neurons and
-- 900 synapses of the looming-to-escape pathway. Every synapse below is real, with its real sign;
-- the sampling is ours (54 of the LC4 cells, 55 of LPLC2, ranked by how much they project
-- toward the giant fibre) because the full population is 311 neurons and 20,607 synapses, which does
-- not compile in 48 KiB of Lua heap.
-- Neuron order: [1..54] LC4, [55..109] LPLC2, [110..121] LC10a, [122..148] intermediates, [149..150] giant fibre.
-- Synapse weight = byte value (signed, -127..127) times 5.8189 raw synapse counts.
local C = {}
C.n = 150
C.n_lc4 = 54
C.n_lplc2 = 55
C.n_lc10a = 12
C.eye_last = 109          -- neurons 1..eye_last are LC4/LPLC2: the lesion target
C.lc10a_first = 110
C.lc10a_last = 121
C.gf_first = 149
C.gf_last = 150
C.n_edges = 900
C.w_scale = 5.818898
-- outgoing edges grouped by source neuron; colptr[i]..colptr[i+1]-1 are neuron i's edges
C.colptr = {0,9,16,25,29,38,43,50,55,60,66,75,81,88,96,102,107,114,119,129,136,145,152,157,166,173,180,183,191,200,204,208,214,222,231,236,242,249,257,263,270,277,283,289,294,299,306,310,316,322,330,337,342,348,354,364,370,379,388,399,405,415,421,425,432,440,446,451,457,462,472,480,486,493,499,504,508,511,522,528,531,536,538,544,552,559,564,572,575,582,590,593,596,601,610,620,627,631,634,638,647,653,659,664,667,677,677,679,683,688,688,689,689,689,689,689,689,689,689,689,689,689,702,711,719,728,735,740,752,760,766,776,787,796,806,809,817,823,832,841,844,848,855,864,870,880,885,889,892,895,900}
C.post = "\3\11\21\24\124\132\138\144\150\18\53\124\132\138\141\150\1\21\24\41\124\132\138\144\150\124\132\138\150\7\19\39\52\132\138\139\141\150\36\124\132\138\150\5\28\132\138\139\141\150\128\134\147\148\149\127\128\134\148\149\19\132\138\139\141\150\1\21\24\51\124\132\138\144\150\25\132\138\139\141\150\14\45\48\127\128\134\149\13\15\30\44\127\128\134\149\9\33\127\128\134\149\51\124\132\138\150\4\24\53\124\132\138\150\124\132\138\139\150\5\10\34\39\124\132\138\139\141\150\22\128\134\146\147\148\149\3\11\24\31\41\124\132\144\150\20\40\128\134\147\148\149\27\124\132\138\150\1\3\11\17\51\124\132\138\150\12\50\124\132\138\139\150\29\43\128\134\147\148\149\132\138\150\7\19\34\132\138\139\141\150\20\22\26\43\54\128\134\147\149\14\128\134\149\124\132\138\150\33\44\127\128\134\149\9\15\32\48\127\128\134\149\5\10\28\50\124\132\139\141\150\4\124\132\138\150\6\23\124\132\138\150\28\124\132\138\139\141\150\29\40\128\134\146\147\148\149\5\19\37\132\138\150\29\38\128\134\147\148\149\3\11\124\132\138\144\150\127\128\134\147\148\149\29\40\128\134\146\149\32\127\128\134\149\13\127\128\134\149\47\127\128\134\147\148\149\127\128\148\149\13\15\127\128\134\149\10\124\132\138\141\150\12\25\28\124\132\139\141\150\11\16\18\53\124\138\150\5\124\132\138\150\17\124\132\138\144\150\40\127\128\134\148\149\61\65\66\67\74\78\96\105\134\149\67\71\102\123\134\149\15\72\78\94\99\103\134\140\149\64\70\79\86\87\101\138\144\150\63\70\73\83\89\95\100\101\138\144\150\73\81\90\95\144\150\55\57\67\71\78\80\82\94\134\149\66\71\72\84\134\149\4\109\144\150\58\70\87\98\101\144\150\55\66\67\71\80\102\134\149\62\65\67\134\142\149\55\56\102\105\149\66\71\91\105\134\149\56\74\96\103\149\59\64\87\89\95\100\101\135\144\150\56\62\68\78\105\134\140\149\57\62\103\134\140\149\59\86\89\93\129\138\150\61\69\75\105\134\149\74\85\108\134\149\45\62\96\149\109\144\150\55\57\61\68\71\76\94\99\103\140\149\58\70\87\100\144\150\134\142\149\87\100\135\144\150\134\149\58\90\95\138\144\150\57\62\82\94\96\108\134\149\71\72\75\94\97\134\149\73\89\104\138\150\58\59\64\70\79\81\144\150\90\95\150\86\88\93\129\138\144\150\60\83\88\92\95\101\135\150\68\80\149\2\18\144\73\89\138\144\150\55\57\66\68\85\96\108\134\149\60\70\77\81\88\90\93\138\144\150\57\68\75\84\94\140\149\67\85\134\149\64\144\150\57\78\134\149\59\60\70\77\79\81\101\144\150\58\70\100\138\144\150\56\65\67\105\134\149\57\72\134\140\149\86\144\150\66\67\68\71\74\75\97\102\134\149\22\149\66\75\142\149\1\21\59\60\144\113\123\124\126\129\132\133\138\141\142\144\145\149\150\122\127\128\129\134\136\142\149\150\122\130\132\135\138\144\145\150\122\123\126\129\136\138\142\149\150\122\123\129\136\142\149\150\123\128\134\143\149\8\122\123\127\131\132\133\134\142\143\149\150\122\123\131\133\138\142\149\150\122\123\124\143\149\150\122\123\128\129\132\138\142\145\149\150\122\123\124\128\129\131\133\138\142\149\150\122\123\128\129\132\142\145\149\150\122\123\127\128\129\132\142\143\149\150\124\140\150\122\123\125\129\138\142\149\150\12\132\138\141\144\150\122\123\124\128\129\132\142\149\150\10\18\37\49\50\52\138\141\150\127\133\149\7\137\139\150\122\123\129\131\134\149\150\122\123\127\130\134\142\147\149\150\3\122\124\129\130\150\122\123\124\129\132\133\138\142\149\150\128\134\147\148\149\8\146\148\149\146\147\149\122\123\142\122\124\129\130\138"
C.w = "\2\2\2\2\7\5\3\3\9\2\2\3\7\2\3\11\2\2\2\2\8\5\2\3\14\3\4\4\9\3\3\2\2\7\4\3\2\14\3\3\4\3\10\3\3\3\3\4\4\9\9\4\2\2\12\3\7\5\3\8\2\4\3\4\3\11\2\2\2\2\4\5\4\2\15\3\5\2\1\2\8\3\2\3\8\7\4\11\3\1\2\1\6\7\5\9\1\2\2\8\6\8\2\2\4\3\11\2\2\2\7\3\2\14\3\2\2\2\9\2\2\2\2\2\4\3\2\4\11\2\5\4\2\4\2\10\1\1\2\2\2\7\3\2\9\2\2\5\3\4\3\10\2\2\2\3\11\3\2\2\2\2\7\2\2\10\2\2\3\3\1\3\9\2\2\3\3\3\3\6\3\3\6\3\3\2\4\3\3\2\7\2\2\2\2\2\5\2\2\10\2\5\4\9\5\2\2\6\2\2\4\5\3\11\1\2\3\2\5\4\3\6\2\2\2\2\2\2\2\4\7\2\5\3\2\8\3\2\4\4\2\7\3\3\5\2\1\3\10\2\2\6\4\2\3\2\7\2\2\2\5\3\12\2\2\4\3\5\4\10\2\1\5\2\2\2\7\2\2\2\2\3\8\2\2\6\2\2\8\1\4\4\3\7\2\5\2\1\8\2\3\3\2\2\2\6\4\3\3\7\2\1\4\2\2\6\2\4\3\4\2\13\2\2\2\2\2\3\1\9\1\2\2\2\4\3\7\2\2\4\3\11\2\5\2\4\2\11\2\2\4\4\2\9\2\4\2\3\2\2\2\2\2\7\2\2\2\1\4\5\1\3\2\2\2\3\2\3\6\4\2\2\2\2\2\2\7\7\2\4\2\2\2\1\2\2\1\3\8\2\2\2\1\4\10\3\1\1\2\2\1\2\2\1\7\2\2\3\3\3\8\2\2\4\2\3\2\2\2\2\5\6\2\3\1\2\2\1\3\6\2\2\2\2\2\7\3\1\3\2\8\2\2\2\2\2\5\2\2\2\2\7\3\3\3\1\2\2\2\2\3\8\2\2\2\2\2\3\2\9\3\2\3\3\2\6\2\2\2\3\2\2\6\2\2\2\2\2\8\2\2\2\2\10\3\1\2\2\2\5\3\2\3\2\2\2\2\1\2\2\3\8\2\1\2\4\5\7\2\2\5\2\2\2\3\5\2\4\2\2\2\1\2\9\1\2\2\2\2\2\2\8\2\2\2\2\2\2\8\2\2\2\2\5\2\2\2\2\2\2\5\7\2\2\11\3\2\1\2\2\2\8\2\2\2\2\2\2\2\8\2\2\8\2\2\2\1\1\2\2\5\2\1\2\2\2\2\2\2\5\2\3\2\2\2\2\2\4\3\9\1\2\2\2\2\2\5\2\2\2\5\1\3\5\2\2\3\6\2\2\2\2\3\2\3\4\6\2\2\3\2\2\8\2\2\2\2\2\6\3\2\2\2\3\2\1\6\2\2\2\2\2\2\1\2\2\8\2\2\2\2\2\6\2\2\2\2\3\1\3\7\3\8\2\2\18\1\4\6\3\10\127\4\6\2\3\19\4\5\92\14\249\251\253\254\252\249\253\185\250\250\254\253\254\254\251\229\228\250\251\249\254\254\235\222\248\253\252\251\205\2\6\13\2\11\5\11\8\3\1\48\3\11\5\2\3\2\2\13\37\4\2\7\5\9\40\251\252\230\238\226\254\239\248\236\229\12\4\2\7\3\9\13\5\1\2\44\253\252\225\234\222\239\242\235\232\5\16\3\11\4\6\6\2\40\5\234\252\212\252\251\253\253\254\252\238\233\1\2\2\2\2\41\11\8\3\5\5\8\3\2\38\2\2\2\2\2\2\2\3\37\234\253\219\2\2\4\37\7\9\3\2\2\24\11\2\3\7\3\2\3\2\27\8\255\251\252\254\254\224\5\2\4\4\2\2\2\2\2\30\3\2\2\6\32\2\2\3\32\3\2\31\1\2\2\3\3\3\2\1"   -- int8 as unsigned bytes


-- fixed point: 1 unit = 1/256 mV, one step = 10 ms. Must match badge/sim_fixed.py exactly.
local V_REST, V_TH = -13312, -11520
local SYN_DECAY = 35            -- exp(-dt/tau_syn) = exp(-10/5) as a 256ths fraction
local GAIN_Q = 75               -- one int8 weight unit in membrane units
local REFRAC = 1                -- one 10 ms step
local STEPS_PER_TICK = 2        -- ticks are nominally 20 ms, the brain runs at 100 Hz
local CUR_MAX = 4000            -- membrane units; threshold is about 1750
local FLASH_MS, JUMP_MS, FLIRT_MS = 160, 260, 3000

local byte, floor, abs = string.byte, math.floor, math.abs
local V, G, REF, SYN = {}, {}, {}, {}
local spk, spk_n = {}, 0
local lesion, gain = false, 3
local loom, last = 0, nil
local gf_count, gf_rate, win_start = 0, 0, 0
local flash_until, jump_until, flirt_until, last_beacon = 0, 0, 0, 0
local tick_ms, led_state = 0, ""
local ui = {}
local radio_ok = false

local function reset_brain()
  for i = 1, C.n do V[i] = V_REST; G[i] = 0; REF[i] = 0; SYN[i] = 0 end
  spk, spk_n = {}, 0
end

-- One 10 ms step of leaky integrate-and-fire over the real connectome. Event driven: only the neurons
-- that fired last step push current, so the cost is spikes times out-degree, not the whole matrix.
local function step(cur, flirt)
  local syn, colptr, post, w = SYN, C.colptr, C.post, C.w
  for i = 1, C.n do syn[i] = 0 end
  for k = 1, spk_n do
    local i = spk[k]
    if not (lesion and i <= C.eye_last) then
      for e = colptr[i] + 1, colptr[i + 1] do
        local wv = byte(w, e)
        if wv > 127 then wv = wv - 256 end
        local p = byte(post, e)
        syn[p] = syn[p] + wv * GAIN_Q
      end
    end
  end
  local n_new, fired = 0, {}
  local eye_last, gf_first = C.eye_last, C.gf_first
  local lc_a, lc_b = C.lc10a_first, C.lc10a_last
  local gf_now = 0
  for i = 1, C.n do
    local g = floor(G[i] * SYN_DECAY / 256) + syn[i]
    G[i] = g
    if REF[i] > 0 then
      REF[i] = REF[i] - 1
      V[i] = V_REST
    else
      local inj = 0
      if i <= eye_last then inj = cur
      elseif flirt and i >= lc_a and i <= lc_b then inj = 2400 end
      local v = V[i] + floor((V_REST - V[i] + g + inj) / 2)
      if v >= V_TH then
        V[i] = V_REST
        REF[i] = REFRAC
        n_new = n_new + 1
        fired[n_new] = i
        if i >= gf_first then gf_now = gf_now + 1 end
      else
        V[i] = v
      end
    end
  end
  spk, spk_n = fired, n_new
  return gf_now
end

local function set_leds(r, g, b)
  badge.led.set_all(r, g, b)
  badge.led.show()
end

function on_enter(root)
  gain = badge.store.get_int("gain", 3)
  reset_brain()

  local bg = badge.ui.box(root, 320, 240)
  bg:style({ bg_color = 0x000000, border_width = 0 })
  bg:set_pos(0, 0)

  local title = badge.ui.label(root, "FlyBadge")
  title:style({ text_color = 0xFF715B, text_font = 20 })
  title:align("top_left", 10, 8)

  ui.sub = badge.ui.label(root, C.n .. " real neurons   " .. C.n_edges .. " real synapses")
  ui.sub:style({ text_color = 0x888888, text_font = 14 })
  ui.sub:align("top_left", 10, 32)

  ui.fly = badge.ui.label(root, "***")
  ui.fly:style({ text_color = 0xFFFFFF, text_font = 24 })
  ui.fly:set_pos(140, 110)

  ui.gf = badge.ui.label(root, "giant fibre  0 Hz")
  ui.gf:style({ text_color = 0xFFFFFF, text_font = 20 })
  ui.gf:align("top_left", 10, 60)

  ui.state = badge.ui.label(root, "INTACT")
  ui.state:style({ text_color = 0x44DD88, text_font = 18 })
  ui.state:align("top_left", 10, 86)

  ui.drive = badge.ui.bar(root, 0, CUR_MAX, 0)
  ui.drive:set_size(300, 10)
  ui.drive:set_pos(10, 160)
  ui.drive:style({ bg_color = 0x222222 })

  ui.perf = badge.ui.label(root, "")
  ui.perf:style({ text_color = 0x666666, text_font = 14 })
  ui.perf:align("bottom_left", 10, -26)

  ui.hint = badge.ui.label(root, "swat me    B lesion    A restore    UP/DOWN gain")
  ui.hint:style({ text_color = 0x888888, text_font = 14 })
  ui.hint:align("bottom_left", 10, -8)

  badge.led.clear(); badge.led.show()
  led_state = "o"
  win_start = badge.sys.ms()

  radio_ok = badge.radio.enable()
  if radio_ok then
    badge.radio.on_recv(function(mac, rssi, payload)
      if payload == "FLY1" then flirt_until = badge.sys.ms() + FLIRT_MS end
    end)
  end
end

function on_tick()
  local t0 = badge.sys.ms()

  -- Looming, from the only sensor the badge has. There is no light sensor on this hardware, so the
  -- stimulus is the swat itself: a hand coming down moves the badge, and the accelerometer reports it.
  -- Per-axis change catches a rotation as well as a shove, which a magnitude alone would miss.
  local x, y, z = badge.sensor.accel()
  local jerk = 0
  if x then
    if last then jerk = abs(x - last[1]) + abs(y - last[2]) + abs(z - last[3])
    else last = {} end
    last[1], last[2], last[3] = x, y, z
  end
  if badge.sensor.shake() then jerk = jerk + 400 end
  loom = floor(loom * 3 / 4) + jerk        -- leaky, so one swat drives the eye for a few ticks
  local cur = loom * gain
  if cur > CUR_MAX then cur = CUR_MAX end

  local now = badge.sys.ms()
  local flirt = now < flirt_until
  local gf_tick = 0
  for _ = 1, STEPS_PER_TICK do
    gf_tick = gf_tick + step(cur, flirt)
  end
  gf_count = gf_count + gf_tick
  if gf_tick > 0 then                      -- this tick's spikes, not the whole reporting window
    flash_until, jump_until = now + FLASH_MS, now + JUMP_MS
  end

  -- LEDs: white on an escape spike, pink while another badge is nearby, one red dot when lesioned.
  -- Written only when the state changes, so an idle tick costs no native calls.
  local want = (now < flash_until) and "f" or (flirt and "p" or (lesion and "l" or "o"))
  if want ~= led_state then
    led_state = want
    if want == "f" then set_leds(255, 255, 255)
    elseif want == "p" then set_leds(120, 20, 60)
    elseif want == "l" then badge.led.clear(); badge.led.set(1, 60, 0, 0); badge.led.show()
    else badge.led.clear(); badge.led.show() end
  end
  ui.drive:set_value(cur)

  ui.fly:set_pos(140, now < jump_until and 70 or 110)

  if radio_ok and now - last_beacon > 1000 then
    last_beacon = now
    badge.radio.send("FLY1")
  end

  tick_ms = badge.sys.ms() - t0
  if now - win_start >= 1000 then
    gf_rate = floor(gf_count * 1000 / (now - win_start) / 2)
    gf_count, win_start = 0, now
    ui.gf:set_text("giant fibre  " .. gf_rate .. " Hz")
    local st = badge.sys.stats()
    ui.perf:set_text(tick_ms .. " ms/tick   " .. floor(tick_ms / STEPS_PER_TICK) .. " ms/step   heap "
      .. floor(st.lua_used / 1024) .. "k   gain " .. gain)
  end
end

function on_button(button, kind)
  if kind ~= badge.input.KIND.PRESSED then return end
  local B = badge.input.BUTTON
  if button == B.B then
    lesion = true
    ui.state:set_text("LC4 + LPLC2 LESIONED")
    ui.state:style({ text_color = 0xFF4444 })
  elseif button == B.A then
    lesion = false
    ui.state:set_text("INTACT")
    ui.state:style({ text_color = 0x44DD88 })
  elseif button == B.UP then
    gain = math.min(40, gain + 1)
  elseif button == B.DOWN then
    gain = math.max(1, gain - 1)
  elseif button == B.START then
    reset_brain()
    loom = 0
  end
end

function on_exit()
  badge.store.set_int("gain", gain)
  badge.led.clear()
  badge.led.show()
  if radio_ok then badge.radio.on_recv(nil); badge.radio.disable() end
end

-- Test hook. badge/test_lua.lua runs this exact step() against badge/sim_fixed.py to confirm the
-- integer arithmetic agrees spike for spike. Nothing on the badge ever reads it.
_G.__flybadge_test = {
  C = C,
  step = function(cur, flirt) return step(cur, flirt) end,
  reset = reset_brain,
  spikes = function() return spk, spk_n end,
  set_lesion = function(v) lesion = v end,
}
